# Generated by Django 4.1.3 on 2023-01-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Жанр')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Создание Жанров',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_movie', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Дата выхода')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('genres', models.ManyToManyField(to='movie_view.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильмы',
                'verbose_name_plural': 'Создание Фильмов',
            },
        ),
    ]
